// <auto-generated />
using System;
using Masuit.MyBlogs.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masuit.MyBlogs.Core.Infrastructure.Migrations.Logger
{
    [DbContext(typeof(LoggerDbContext))]
    [Migration("20260930061232_AddHttpRequestLogs")]
    partial class AddHttpRequestLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masuit.MyBlogs.Core.Common.PerformanceCounter", b =>
                {
                    b.Property<string>("ServerIP")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<float>("CpuLoad")
                        .HasColumnType("real");

                    b.Property<float>("DiskRead")
                        .HasColumnType("real");

                    b.Property<float>("DiskWrite")
                        .HasColumnType("real");

                    b.Property<float>("Download")
                        .HasColumnType("real");

                    b.Property<float>("MemoryUsage")
                        .HasColumnType("real");

                    b.Property<float>("ProcessCpuLoad")
                        .HasColumnType("real");

                    b.Property<float>("ProcessMemoryUsage")
                        .HasColumnType("real");

                    b.Property<float>("Upload")
                        .HasColumnType("real");

                    b.HasKey("ServerIP", "Time");

                    b.ToTable("PerformanceCounter");
                });

            modelBuilder.Entity("Masuit.MyBlogs.Core.Models.Entity.HttpRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionInfo")
                        .HasColumnType("text");

                    b.Property<string>("IP")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsException")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("RequestParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("IsException", "Time");

                    b.ToTable("HttpRequestLog");
                });

            modelBuilder.Entity("Masuit.MyBlogs.Core.Models.Entity.RequestLogDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp");

                    b.Property<string>("City")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Country")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IP")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(4096)
                        .IsUnicode(true)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id", "Time");

                    b.ToTable("RequestLogDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
