// <auto-generated />
using System;
using Masuit.MyBlogs.Core.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masuit.MyBlogs.Core.Infrastructure.Migrations.Logger
{
    [DbContext(typeof(LoggerDbContext))]
    partial class LoggerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masuit.MyBlogs.Core.Common.PerformanceCounter", b =>
                {
                    b.Property<string>("ServerIP")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.Property<float>("CpuLoad")
                        .HasColumnType("real");

                    b.Property<float>("DiskRead")
                        .HasColumnType("real");

                    b.Property<float>("DiskWrite")
                        .HasColumnType("real");

                    b.Property<float>("Download")
                        .HasColumnType("real");

                    b.Property<float>("MemoryUsage")
                        .HasColumnType("real");

                    b.Property<float>("ProcessCpuLoad")
                        .HasColumnType("real");

                    b.Property<float>("ProcessMemoryUsage")
                        .HasColumnType("real");

                    b.Property<float>("Upload")
                        .HasColumnType("real");

                    b.HasKey("ServerIP", "Time");

                    b.ToTable("PerformanceCounter");
                });

            modelBuilder.Entity("Masuit.MyBlogs.Core.Models.Entity.RequestLogDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp");

                    b.Property<string>("City")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Country")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("IP")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Network")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(4096)
                        .IsUnicode(true)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id", "Time");

                    b.ToTable("RequestLogDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
